[package]
name = "image-upload-microservice"
version = "0.1.0"
authors = ["hazzard <thehazzard@gmail.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.27"
futures = "0.1.26"
failure = "0.1.5"
tokio = "0.1.19"
rand = "0.5"
regex = "1.1.6"
lazy_static = "1.3.0"
hyper-staticfile = "0.3.1"